### ISSUE TITLE
Select em Cargos na tela de Adicionar

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#21]
Ao inves de colocar um input text colocar um select que contenha todos os cargos, nao permitindo erros gramaticos ou inserção de cargos que nao existam

**Comment by tiagolimar** [comment]
E quais são os cargos a serem adicionados?

**Comment by EduardoBerot** [comment]
Estagiário, Auxiliar, Supervisor, Coordenador e Dono
