### ISSUE TITLE
Adicionar botao de editar na tabela de membros 

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#22]
Colocar na tabela de membros um botão de editar, que quando clicado, leva para a tela de adicionar com os inputs preenchidos com as informações que ja existem, podendo altera-las. Dessa forma, nao haverá necessidade de excluir um membro e coloca-lo dnv com a alteração feita, quando algum cargo for concedido a alguém, por exemplo.

**Comment by tiagolimar** [comment]
Não fui atrás do ícone de lápis pra fazer o botão, por enquanto estou usando o símbolo de deslike. Você pode fazer essa substituição posteriormente?

**Comment by EduardoBerot** [comment]
Consigo sim, obrigado por avisar

**Comment by tiagolimar** [comment]
![image](https://github.com/EduardoBerot/Eternity/assets/47084105/712c324d-5cea-4ddb-85ae-21ed85e31431)

Fazer uma estilização CSS, a minha ideia seria fazer dois botões na parte de baixo lado a lado, um vermelho (botão de voltar) e o outro normal, como os botões dos outros formulários. Esse elemento "Voltar" já está funcional, só precisa estilizar ele.

**Comment by tiagolimar** [comment]
![image](https://github.com/EduardoBerot/Eternity/assets/47084105/0b408281-c147-43fd-90f0-1046bdc419d6)

Trecho do código onde está esses botões, você poderia usar o arquivo cadastro.css
