### ISSUE TITLE
Tornar a idade dinâmica 

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#23]
Na parte de juntar-se, ao invés de colocar a idade, colocar um select de data de nascimento, desta forma, na tabela de membros, converter para numero a idade da pessoa, sendo possível deixar a idade dinâmica, atualizando sempre que a pessoa completar mais um ano de vida

**Comment by tiagolimar** [comment]
Puxa, faz todo o sentido
