### ISSUE TITLE
Data no Adicionar

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#24]
Ao colocar uma data em adicionar, quando ele leva as informaçoes pra tabela de membros, acaba reduzindo 1 dia, por exemplo: se eu botei a data 05/05/2024 no cadastro, na tabela de membros a data fica 04/05/2024

**Comment by tiagolimar** [comment]
Há um problema nesta função do arquivo global.js, ela recebe uma data e retorna outra com 1 dia de diferença, ainda não consegui resolver, mas estou trabalhando nisso:

![image](https://github.com/EduardoBerot/Eternity/assets/47084105/e4113c46-a331-4357-8525-c70278548720)

**Comment by tiagolimar** [comment]
Pra resolver temporariamente eu fiz essa variável add, mas essa solução ainda não é completa, pois se for dia 31, por exemplo, ele vai retornar uma data inválida porque não existe dia 32.

**Comment by tiagolimar** [comment]
Resolvido juntamente com o issue #22.
