### ISSUE TITLE
Criação do LogChat

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#28]
Ao clicar em excluir um membro, abrir um window alert cm uma text area (algo nesse sentido) para preencher o motivo, e ao aceitar, levar para uma tabela onde mostra o historico de todas as expulsoes, constando nick, idade, data entrada, data saida e o motivo do kick.

**Comment by tiagolimar** [comment]
Deverá existir a possibilidade de desbanir também?

**Comment by EduardoBerot** [comment]
acho que nao ha necessidade pois o logchat so ira constar expulsoes, a blacklist acredito ser melhor fazer por outra sistematica e até outra lista. 

seria interessante fazer ate um limite pra ver esses dados, tipo de depois de X tempo eles somem.

**Comment by tiagolimar** [comment]
### Banimento
- 	Incluir um botão de banimento na seção de membros
- 	banimento exige frase de confirmação: "Escreva a frase: '${recrutador} baniu o ${player}' "
- 	Gera um log de banimento
- 	Membros banidos não conseguem fazer novas solicitações
- 	Membros banidos não podem ser adicionados por um staff

### Remoção

- 	Gerar um log de remoção

### LogChat

- 	Criar link "Histórico"
- 	O histórico é exibido em forma de tabela (colunas: evento, recrutador, nick, comentário e data)
- 	Eventos que geram um log: confirmar solicitação, adicionar um jogador, remover um jogador, banir um jogador


```
Evento					Recrutador	Nick    Comentário  	Data
Confirmação de Solicitação		...		...	...		dd/mm/yyyy
Adição de Jogador			...		...	...		dd/mm/yyyy
Remoção de Jogador			...		...	Motivo		dd/mm/yyyy
Banimento de Jogador			...		...	Motivo		dd/mm/yyyy
```

**Comment by tiagolimar** [comment]
- [x] confirmar solicitação
- [x] adicionar um jogador
- [x] remover um jogador
- [x] banir um jogador

**Comment by EduardoBerot** [comment]
> Deverá existir a possibilidade de desbanir também?
> 

Deverá, porém, a nível de informação: só poderão haver desbanimentos dentro da Eternity através do consenso de todos os membros da staff do Clan.
