### ISSUE TITLE
Motivos de kicks e bans nos selects das respectivas ações.

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#32]
Adicionar, os seguintes motivos nos selects:

Lista de motivos de kicks
- Desrespeitar as regras do clan
- Abandono
- Inatividade

Lista de motivos de bans:
- Desrespeitar as regras do servidor
- Griffar farms
- Reincidente em kicks
- Desertar e/ou iniciar motim de outro clan

Nota: a adição, remoção ou edição dos motivos poderá ser feita posteriormente, usar estes por enquanto.

**Comment by tiagolimar** [comment]
O significado de "kick" e "ban" seriam:

kick = Estou lhe expulsando, mas pode voltar quando quiser
ban = Vai embora e volte NUNCA MAIS.

?

**Comment by tiagolimar** [comment]
O motivo "Desrespeitar as regras do clan" me parece ser muito impreciso e pode gerar confusões, não seria melhor listar de fato as regras que não devem ser desrespeitadas?

**Comment by EduardoBerot** [comment]
> O significado de "kick" e "ban" seriam:
> 
> kick = Estou lhe expulsando, mas pode voltar quando quiser
> ban = Vai embora e volte NUNCA MAIS.
> 
> ?

Isto. O kick é algo mais subjetivo, por isso engloba inatividade e abandono pelo player. Enquanto o ban é algo que leva a pessoa pra blacklist e pra sair de lá só com decisão conjunta de todos os membros da staff.

**Comment by EduardoBerot** [comment]
> O motivo "Desrespeitar as regras do clan" me parece ser muito impreciso e pode gerar confusões, não seria melhor listar de fato as regras que não devem ser desrespeitadas?

Como se tratam somente de duas regras globais dentro do game, pensei em englobalos. Mas, se formos expandir, seria:

- Desrespeitar regras de build (construções em desacordo com o tema da cidade) 
- Conduta moral inapropriada leve (desonestidade, falta de respeito e desunião)

Nota: os parenteses são descritivos, se os títulos dos motivos forem levados para o select, as informações contidas entre os parenteses não deverão aparecer.

**Comment by EduardoBerot** [comment]
Repensando algumas coisas, alguns motivos de "kicks" não deverão haver o sentido de expulsão, mas sim de correção por erro da staff na tabela de membros.

Um caso, seria:

- Equívoco no aceite de solicitação

Obs: neste caso, ao excluir um membro, o motivo seria que ele se quer passou a ser membro in game, justamente por alguém da staff ter aceito de forma equivocada a solicitação do mesmo.

Acredito veementemente, que situações como essas, provavelmente aparecerão durante o uso do site, então é algo que fica aberto a incrementação.

**Comment by EduardoBerot** [comment]
Redefinindo os motivos conforme comentários acima, ficariam desta forma:

Lista de motivos de kicks:

- Desrespeitar regras de build
- Conduta moral inapropriada
- Abandono
- Inatividade
- Equívoco no aceite da solicitação

Lista de motivos de bans:

- Desrespeitar as regras do servidor 
- Griffar farms
- Reincidente em kicks
- Desertar e/ou iniciar motim de outro clan
