### ISSUE TITLE
Sistemática de aniversários 

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#34]
Criar um sistema de avisos e mensagem automática dentro do discord do Clan aonde irá parabenizar os membros que fizerem aniversário. Isso será possível agora que já possuímos a idade de nossos membros dinâmicas e a data de nascimento dos mesmos.

A criação de uma sistemática do tipo, que talvez só seria possível pela organização do site, poderá aumentar o engajamento entre a relação Clan x membros.

**Comment by tiagolimar** [comment]
A funcionalidade já está quase pronta, falta apenas a URL de integração com o Discord do clan.

**Comment by tiagolimar** [comment]
[25/6 16:12] MIN_Ducred: @⁨Tiago Lima⁩ segue url do webhook [url omitida]
[25/6 16:13] MIN_Ducred: a mensagem sera enviada nos canais da staff
[25/6 16:15] MIN_Ducred: id do cargo fundado: 1021451365781884978
id do cargo dono: 1021451446086008872
id do cargo coordenador: 1021451519754764421
id do cargo supervisor: 1021451558694694982
id do cargo auxiliar: 1021451595738775562

@⁨Tiago Lima⁩
[25/6 16:16] MIN_Ducred: a mensagem q deve vir eh a seguinte
[25/6 16:22] MIN_Ducred: "O player (nick) está fazendo aniversario hoje! Mande a mensagem abaixo para ele copiando e colando ou faça a sua para parabeniza-lo:

A Eternidade gostaria de te parabenizar e te desejar muita saúde, felicidade e sucesso! Que continue sendo esta pessoa incrível na jornada da sua vida e busque sempre o progresso. De uma passada lá no Apocalipse para receber a sua lembrancinha.
Uni-vos pela Eternidade"

ai junto com o texto pensei em anexar uma imagem, provavelmente naquele wallpaper generator tem alguma coisa de aniversario.

**Comment by EduardoBerot** [comment]
URL: https://discord.com/api/webhooks/1255239092124389516/65PMfileZQ1zDQPgOvdX0VViAq2MQHl0oZ0KyWiY1wxG8ZlfCRDznoHa4NjDsy4AorqT

Mensagem:
Saudações Eternos! (negrito e italico)

O ${cargo} ${nick} está completando mais um ano de vida!
A Eternity gostaria de te parabenizar e te desejar muita saúde, felicidade e sucesso! Que continue sendo esta pessoa incrível na jornada da sua vida e busque sempre o progresso. De uma passada lá no Apocalipse para receber a sua lembrancinha.

Uni-vos pela Eternidade (negrito e italico)
@membros (id do cargo: 1021451668606423052)

![novaskin-wallpaper-bday](https://github.com/EduardoBerot/Eternity/assets/105256677/ca79a0bd-482d-4e23-a6e4-92a751eadae7)

**Comment by tiagolimar** [comment]
Resolvido!
![image](https://github.com/EduardoBerot/Eternity/assets/47084105/9b2665c5-8682-47b8-bd99-fc776d0ecea3)
