### ISSUE TITLE
Bugs do logchat 

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#36]
Ao excluir alguém, está puxando o recrutador daquela pessoa e não quem expulsou

Evento de abertura de solicitação nomeado de "adição de player", deve ser "abertura de solicitação" e não deve puxar nome de nenhum recrutador, o campo deve ficar vazio, constando só a data e que abriu a solicitação

**Comment by tiagolimar** [comment]
- [x] Excluir alguém puxa o nome de quem expulsou e não do recrutador
- [x] Solicitações devem gerar um evento do tipo "Solicitação de admissão"
- [x] Solicitações não devem ter um recrutador
