### ISSUE TITLE
Mensagens Temporárias no canal de Aniversariantes + Bug Everyone 

### ISSUE THREAD

**Issue by EduardoBerot** [EduardoBerot/Eternity#38]
As mensagens de aniversario podem ser temporárias, tornando o canal algo mais dinâmico.

Pelo próprio discord, nao existe a configuração de temporizador de mensagens, porem, achei um vídeo que pode ser útil:
https://www.youtube.com/watch?v=FHKrAoqYVAY

Além disso, o @Everyone dentro da mensagem nao está dando a notificação para quem foi marcado.
Uma possivel solução seria puxar a menção a everyone para fora do "topico" (a area destacada da mensagem), no lugar de onde esta escrito: "Comunicado"

**Comment by tiagolimar** [comment]
Andei dando uma analisada na questão, cheguei as seguintes conclusões:

1. Parece que não existe de fato uma mensagem "temporária" que se apaga sozinha depois de um tempo, nesse vídeo ele deve estar falando em mensagem temporária mais no sentido de mensagens que são enviadas automaticamente de tempos em tempos.

2. Mas é possível fazer a exclusão de mensagens antigas, com mais de 24 horas, por  exemplo, eu só não consegui configurar isso ainda. Até lá as mensagens podem ser excluídas manualmente.

3. Esse sistema de mensagem tem uma falha que é que ele depende que pelo menos uma pessoa acesse a sessão de administração do site, pois a verificação acontece quando alguém acessa o site. Eu poderia configurar para que fosse uma verificação independente, que acontecesse a cada 24 horas, por exemplo, mas pra isso seria necessário um servidor que realmente funcionasse 24 horas sem hirbenar.

4. Eu corrigi pelo menos a parte do @everyone.
